name: Deploy YAML to S3

on:
  push:
    branches:
      - main  # Only run when changes are pushed to main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.x

    - name: Run main.py
      run: python main.py

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2  # Change to your region

    - name: Upload YAML file to S3
      run: |
        aws s3 cp config.yaml s3://sugnyani-patil/Config/
